name: actions

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: '**/*.md'

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
